// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: quote.proto

package server

import (
	"context"

	"github.com/nmg988rbdv-svg/go-zero_columbina/app/quote/rpc/internal/logic"
	"github.com/nmg988rbdv-svg/go-zero_columbina/app/quote/rpc/internal/svc"
	"github.com/nmg988rbdv-svg/go-zero_columbina/app/quote/rpc/pb"
)

type QuoteServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedQuoteServiceServer
}

func NewQuoteServiceServer(svcCtx *svc.ServiceContext) *QuoteServiceServer {
	return &QuoteServiceServer{
		svcCtx: svcCtx,
	}
}

// 获取k线
func (s *QuoteServiceServer) GetKline(ctx context.Context, in *pb.GetKlineReq) (*pb.GetKlineResp, error) {
	l := logic.NewGetKlineLogic(ctx, s.svcCtx)
	return l.GetKline(in)
}

// 获取24小时行情
func (s *QuoteServiceServer) GetTicker(ctx context.Context, in *pb.GetTickerReq) (*pb.GetTickerResp, error) {
	l := logic.NewGetTickerLogic(ctx, s.svcCtx)
	return l.GetTicker(in)
}

// 获取tick
func (s *QuoteServiceServer) GetTick(ctx context.Context, in *pb.GetTickReq) (*pb.GetTickResp, error) {
	l := logic.NewGetTickLogic(ctx, s.svcCtx)
	return l.GetTick(in)
}
