// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: app/quote/rpc/pb/quote.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KlineType int32

const (
	KlineType_Unknown KlineType = 0
	// 1分钟
	KlineType_Min1 KlineType = 1
	// 5分钟
	KlineType_Min5 KlineType = 2
	// 10分钟
	KlineType_Min10 KlineType = 3
	// 15分钟
	KlineType_Min15 KlineType = 4
	// 30分钟
	KlineType_Min30 KlineType = 5
	// 1小时
	KlineType_Hour1 KlineType = 6
	// 4小时
	KlineType_Hour4 KlineType = 7
	// 1天
	KlineType_Day1 KlineType = 8
	// 1周
	KlineType_Week1 KlineType = 9
	// 1个月
	KlineType_Month1 KlineType = 10
)

// Enum value maps for KlineType.
var (
	KlineType_name = map[int32]string{
		0:  "Unknown",
		1:  "Min1",
		2:  "Min5",
		3:  "Min10",
		4:  "Min15",
		5:  "Min30",
		6:  "Hour1",
		7:  "Hour4",
		8:  "Day1",
		9:  "Week1",
		10: "Month1",
	}
	KlineType_value = map[string]int32{
		"Unknown": 0,
		"Min1":    1,
		"Min5":    2,
		"Min10":   3,
		"Min15":   4,
		"Min30":   5,
		"Hour1":   6,
		"Hour4":   7,
		"Day1":    8,
		"Week1":   9,
		"Month1":  10,
	}
)

func (x KlineType) Enum() *KlineType {
	p := new(KlineType)
	*p = x
	return p
}

func (x KlineType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KlineType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_quote_rpc_pb_quote_proto_enumTypes[0].Descriptor()
}

func (KlineType) Type() protoreflect.EnumType {
	return &file_app_quote_rpc_pb_quote_proto_enumTypes[0]
}

func (x KlineType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KlineType.Descriptor instead.
func (KlineType) EnumDescriptor() ([]byte, []int) {
	return file_app_quote_rpc_pb_quote_proto_rawDescGZIP(), []int{0}
}

type GetKlineReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 开始时间
	StartTime int64 `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// 结束时间
	EntTime int64 `protobuf:"varint,2,opt,name=ent_time,json=entTime,proto3" json:"ent_time,omitempty"`
	// k线类型
	KlineType KlineType `protobuf:"varint,3,opt,name=kline_type,json=klineType,proto3,enum=pb.KlineType" json:"kline_type,omitempty"`
	// 交易对
	Symbol string `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (x *GetKlineReq) Reset() {
	*x = GetKlineReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKlineReq) ProtoMessage() {}

func (x *GetKlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKlineReq.ProtoReflect.Descriptor instead.
func (*GetKlineReq) Descriptor() ([]byte, []int) {
	return file_app_quote_rpc_pb_quote_proto_rawDescGZIP(), []int{0}
}

func (x *GetKlineReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetKlineReq) GetEntTime() int64 {
	if x != nil {
		return x.EntTime
	}
	return 0
}

func (x *GetKlineReq) GetKlineType() KlineType {
	if x != nil {
		return x.KlineType
	}
	return KlineType_Unknown
}

func (x *GetKlineReq) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetKlineResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KlineList []*GetKlineResp_Kline `protobuf:"bytes,1,rep,name=kline_list,json=klineList,proto3" json:"kline_list,omitempty"`
}

func (x *GetKlineResp) Reset() {
	*x = GetKlineResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKlineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKlineResp) ProtoMessage() {}

func (x *GetKlineResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKlineResp.ProtoReflect.Descriptor instead.
func (*GetKlineResp) Descriptor() ([]byte, []int) {
	return file_app_quote_rpc_pb_quote_proto_rawDescGZIP(), []int{1}
}

func (x *GetKlineResp) GetKlineList() []*GetKlineResp_Kline {
	if x != nil {
		return x.KlineList
	}
	return nil
}

type Ticker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 开
	Open string `protobuf:"bytes,1,opt,name=open,proto3" json:"open,omitempty"`
	// 高
	High string `protobuf:"bytes,2,opt,name=high,proto3" json:"high,omitempty"`
	// 低
	Low string `protobuf:"bytes,3,opt,name=low,proto3" json:"low,omitempty"`
	// 收
	Close string `protobuf:"bytes,4,opt,name=close,proto3" json:"close,omitempty"`
	// 成交额 计价币数量
	Volume string `protobuf:"bytes,5,opt,name=volume,proto3" json:"volume,omitempty"`
	// 成交量 基础币数量
	Amount string `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	// 涨跌幅
	Range string `protobuf:"bytes,9,opt,name=range,proto3" json:"range,omitempty"`
	// 交易对
	Symbol string `protobuf:"bytes,10,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (x *Ticker) Reset() {
	*x = Ticker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ticker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticker) ProtoMessage() {}

func (x *Ticker) ProtoReflect() protoreflect.Message {
	mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticker.ProtoReflect.Descriptor instead.
func (*Ticker) Descriptor() ([]byte, []int) {
	return file_app_quote_rpc_pb_quote_proto_rawDescGZIP(), []int{2}
}

func (x *Ticker) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *Ticker) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *Ticker) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *Ticker) GetClose() string {
	if x != nil {
		return x.Close
	}
	return ""
}

func (x *Ticker) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *Ticker) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Ticker) GetRange() string {
	if x != nil {
		return x.Range
	}
	return ""
}

func (x *Ticker) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetTickerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 交易对
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (x *GetTickerReq) Reset() {
	*x = GetTickerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTickerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickerReq) ProtoMessage() {}

func (x *GetTickerReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickerReq.ProtoReflect.Descriptor instead.
func (*GetTickerReq) Descriptor() ([]byte, []int) {
	return file_app_quote_rpc_pb_quote_proto_rawDescGZIP(), []int{3}
}

func (x *GetTickerReq) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetTickerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticker *Ticker `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
}

func (x *GetTickerResp) Reset() {
	*x = GetTickerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTickerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickerResp) ProtoMessage() {}

func (x *GetTickerResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickerResp.ProtoReflect.Descriptor instead.
func (*GetTickerResp) Descriptor() ([]byte, []int) {
	return file_app_quote_rpc_pb_quote_proto_rawDescGZIP(), []int{4}
}

func (x *GetTickerResp) GetTicker() *Ticker {
	if x != nil {
		return x.Ticker
	}
	return nil
}

type GetTickReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 交易对
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// 多少条
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetTickReq) Reset() {
	*x = GetTickReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTickReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickReq) ProtoMessage() {}

func (x *GetTickReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickReq.ProtoReflect.Descriptor instead.
func (*GetTickReq) Descriptor() ([]byte, []int) {
	return file_app_quote_rpc_pb_quote_proto_rawDescGZIP(), []int{5}
}

func (x *GetTickReq) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetTickReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetDepthReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 交易对
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// 档位
	Level int32 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *GetDepthReq) Reset() {
	*x = GetDepthReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDepthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepthReq) ProtoMessage() {}

func (x *GetDepthReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepthReq.ProtoReflect.Descriptor instead.
func (*GetDepthReq) Descriptor() ([]byte, []int) {
	return file_app_quote_rpc_pb_quote_proto_rawDescGZIP(), []int{6}
}

func (x *GetDepthReq) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetDepthReq) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type GetDepthResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 订单簿版本
	Version int64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// 卖盘
	Asks []*GetDepthResp_Position `protobuf:"bytes,2,rep,name=asks,proto3" json:"asks,omitempty"`
	// 买盘
	Bids []*GetDepthResp_Position `protobuf:"bytes,3,rep,name=bids,proto3" json:"bids,omitempty"`
}

func (x *GetDepthResp) Reset() {
	*x = GetDepthResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDepthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepthResp) ProtoMessage() {}

func (x *GetDepthResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepthResp.ProtoReflect.Descriptor instead.
func (*GetDepthResp) Descriptor() ([]byte, []int) {
	return file_app_quote_rpc_pb_quote_proto_rawDescGZIP(), []int{7}
}

func (x *GetDepthResp) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetDepthResp) GetAsks() []*GetDepthResp_Position {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *GetDepthResp) GetBids() []*GetDepthResp_Position {
	if x != nil {
		return x.Bids
	}
	return nil
}

type Tick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price        string `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`             //价格
	BaseAmount   string `protobuf:"bytes,2,opt,name=baseAmount,proto3" json:"baseAmount,omitempty"`   //计价币数量
	QuoteAmount  string `protobuf:"bytes,3,opt,name=quoteAmount,proto3" json:"quoteAmount,omitempty"` //计价币数量
	Side         int32  `protobuf:"varint,4,opt,name=side,proto3" json:"side,omitempty"`              //1买 2卖
	CreatedAt    int64  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	TakerIsBuyer bool   `protobuf:"varint,6,opt,name=taker_is_buyer,json=takerIsBuyer,proto3" json:"taker_is_buyer,omitempty"`
	Symbol       string `protobuf:"bytes,7,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (x *Tick) Reset() {
	*x = Tick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tick) ProtoMessage() {}

func (x *Tick) ProtoReflect() protoreflect.Message {
	mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tick.ProtoReflect.Descriptor instead.
func (*Tick) Descriptor() ([]byte, []int) {
	return file_app_quote_rpc_pb_quote_proto_rawDescGZIP(), []int{8}
}

func (x *Tick) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Tick) GetBaseAmount() string {
	if x != nil {
		return x.BaseAmount
	}
	return ""
}

func (x *Tick) GetQuoteAmount() string {
	if x != nil {
		return x.QuoteAmount
	}
	return ""
}

func (x *Tick) GetSide() int32 {
	if x != nil {
		return x.Side
	}
	return 0
}

func (x *Tick) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Tick) GetTakerIsBuyer() bool {
	if x != nil {
		return x.TakerIsBuyer
	}
	return false
}

func (x *Tick) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetTickResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TickList []*Tick `protobuf:"bytes,1,rep,name=tick_list,json=tickList,proto3" json:"tick_list,omitempty"`
	Total    int64   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GetTickResp) Reset() {
	*x = GetTickResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTickResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickResp) ProtoMessage() {}

func (x *GetTickResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickResp.ProtoReflect.Descriptor instead.
func (*GetTickResp) Descriptor() ([]byte, []int) {
	return file_app_quote_rpc_pb_quote_proto_rawDescGZIP(), []int{9}
}

func (x *GetTickResp) GetTickList() []*Tick {
	if x != nil {
		return x.TickList
	}
	return nil
}

func (x *GetTickResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetKlineResp_Kline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 开
	Open string `protobuf:"bytes,1,opt,name=open,proto3" json:"open,omitempty"`
	// 高
	High string `protobuf:"bytes,2,opt,name=high,proto3" json:"high,omitempty"`
	// 低
	Low string `protobuf:"bytes,3,opt,name=low,proto3" json:"low,omitempty"`
	// 收
	Close string `protobuf:"bytes,4,opt,name=close,proto3" json:"close,omitempty"`
	// 成交额 计价币数量
	Volume string `protobuf:"bytes,5,opt,name=volume,proto3" json:"volume,omitempty"`
	// 成交量 基础币数量
	Amount string `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	// 开始时间
	StartTime int64 `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// 结束时间
	EndTime int64 `protobuf:"varint,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// 涨跌幅
	Range string `protobuf:"bytes,9,opt,name=range,proto3" json:"range,omitempty"`
	// 交易对
	Symbol string `protobuf:"bytes,10,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (x *GetKlineResp_Kline) Reset() {
	*x = GetKlineResp_Kline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKlineResp_Kline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKlineResp_Kline) ProtoMessage() {}

func (x *GetKlineResp_Kline) ProtoReflect() protoreflect.Message {
	mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKlineResp_Kline.ProtoReflect.Descriptor instead.
func (*GetKlineResp_Kline) Descriptor() ([]byte, []int) {
	return file_app_quote_rpc_pb_quote_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetKlineResp_Kline) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *GetKlineResp_Kline) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *GetKlineResp_Kline) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *GetKlineResp_Kline) GetClose() string {
	if x != nil {
		return x.Close
	}
	return ""
}

func (x *GetKlineResp_Kline) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *GetKlineResp_Kline) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *GetKlineResp_Kline) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetKlineResp_Kline) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetKlineResp_Kline) GetRange() string {
	if x != nil {
		return x.Range
	}
	return ""
}

func (x *GetKlineResp_Kline) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetDepthResp_Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 数量
	BaseAmount string `protobuf:"bytes,1,opt,name=baseAmount,proto3" json:"baseAmount,omitempty"`
	// 价格
	Price string `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	// 金额
	QuoteAmount string `protobuf:"bytes,3,opt,name=quoteAmount,proto3" json:"quoteAmount,omitempty"`
}

func (x *GetDepthResp_Position) Reset() {
	*x = GetDepthResp_Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDepthResp_Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepthResp_Position) ProtoMessage() {}

func (x *GetDepthResp_Position) ProtoReflect() protoreflect.Message {
	mi := &file_app_quote_rpc_pb_quote_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepthResp_Position.ProtoReflect.Descriptor instead.
func (*GetDepthResp_Position) Descriptor() ([]byte, []int) {
	return file_app_quote_rpc_pb_quote_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetDepthResp_Position) GetBaseAmount() string {
	if x != nil {
		return x.BaseAmount
	}
	return ""
}

func (x *GetDepthResp_Position) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GetDepthResp_Position) GetQuoteAmount() string {
	if x != nil {
		return x.QuoteAmount
	}
	return ""
}

var File_app_quote_rpc_pb_quote_proto protoreflect.FileDescriptor

var file_app_quote_rpc_pb_quote_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x70, 0x2f, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x62, 0x2f, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x8d, 0x01, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4b, 0x6c, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x0a,
	0x6b, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x09, 0x6b, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x22, 0xb7, 0x02, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4b, 0x6c, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x0a, 0x6b, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x4b, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x4b, 0x6c, 0x69, 0x6e, 0x65, 0x52,
	0x09, 0x6b, 0x6c, 0x69, 0x6e, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0xef, 0x01, 0x0a, 0x05, 0x4b,
	0x6c, 0x69, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03,
	0x6c, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63,
	0x6c, 0x6f, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0xb6, 0x01, 0x0a,
	0x06, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x69, 0x67, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12,
	0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f,
	0x77, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0x26, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0x33, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22,
	0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x70, 0x62, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x72, 0x22, 0x3a, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x3b,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0xea, 0x01, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70,
	0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x04, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x2d, 0x0a, 0x04, 0x62, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04,
	0x62, 0x69, 0x64, 0x73, 0x1a, 0x62, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x71, 0x75, 0x6f,
	0x74, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xcf, 0x01, 0x0a, 0x04, 0x54, 0x69, 0x63,
	0x6b, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x61, 0x73,
	0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x71, 0x75, 0x6f, 0x74, 0x65,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x71, 0x75,
	0x6f, 0x74, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x64,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x64, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x24, 0x0a, 0x0e,
	0x74, 0x61, 0x6b, 0x65, 0x72, 0x5f, 0x69, 0x73, 0x5f, 0x62, 0x75, 0x79, 0x65, 0x72, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x74, 0x61, 0x6b, 0x65, 0x72, 0x49, 0x73, 0x42, 0x75, 0x79,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0x4a, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x54, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x09, 0x74, 0x69, 0x63,
	0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70,
	0x62, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x52, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x2a, 0x84, 0x01, 0x0a, 0x09, 0x4b, 0x6c, 0x69, 0x6e, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x69, 0x6e, 0x31, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4d,
	0x69, 0x6e, 0x35, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x69, 0x6e, 0x31, 0x30, 0x10, 0x03,
	0x12, 0x09, 0x0a, 0x05, 0x4d, 0x69, 0x6e, 0x31, 0x35, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x4d,
	0x69, 0x6e, 0x33, 0x30, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x6f, 0x75, 0x72, 0x31, 0x10,
	0x06, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x6f, 0x75, 0x72, 0x34, 0x10, 0x07, 0x12, 0x08, 0x0a, 0x04,
	0x44, 0x61, 0x79, 0x31, 0x10, 0x08, 0x12, 0x09, 0x0a, 0x05, 0x57, 0x65, 0x65, 0x6b, 0x31, 0x10,
	0x09, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x31, 0x10, 0x0a, 0x32, 0x9b, 0x01,
	0x0a, 0x0c, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2d,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x4b, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x4b, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x4b, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x2a, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x12, 0x0e, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_quote_rpc_pb_quote_proto_rawDescOnce sync.Once
	file_app_quote_rpc_pb_quote_proto_rawDescData = file_app_quote_rpc_pb_quote_proto_rawDesc
)

func file_app_quote_rpc_pb_quote_proto_rawDescGZIP() []byte {
	file_app_quote_rpc_pb_quote_proto_rawDescOnce.Do(func() {
		file_app_quote_rpc_pb_quote_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_quote_rpc_pb_quote_proto_rawDescData)
	})
	return file_app_quote_rpc_pb_quote_proto_rawDescData
}

var file_app_quote_rpc_pb_quote_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_app_quote_rpc_pb_quote_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_app_quote_rpc_pb_quote_proto_goTypes = []interface{}{
	(KlineType)(0),                // 0: pb.KlineType
	(*GetKlineReq)(nil),           // 1: pb.GetKlineReq
	(*GetKlineResp)(nil),          // 2: pb.GetKlineResp
	(*Ticker)(nil),                // 3: pb.Ticker
	(*GetTickerReq)(nil),          // 4: pb.GetTickerReq
	(*GetTickerResp)(nil),         // 5: pb.GetTickerResp
	(*GetTickReq)(nil),            // 6: pb.GetTickReq
	(*GetDepthReq)(nil),           // 7: pb.GetDepthReq
	(*GetDepthResp)(nil),          // 8: pb.GetDepthResp
	(*Tick)(nil),                  // 9: pb.Tick
	(*GetTickResp)(nil),           // 10: pb.GetTickResp
	(*GetKlineResp_Kline)(nil),    // 11: pb.GetKlineResp.Kline
	(*GetDepthResp_Position)(nil), // 12: pb.GetDepthResp.Position
}
var file_app_quote_rpc_pb_quote_proto_depIdxs = []int32{
	0,  // 0: pb.GetKlineReq.kline_type:type_name -> pb.KlineType
	11, // 1: pb.GetKlineResp.kline_list:type_name -> pb.GetKlineResp.Kline
	3,  // 2: pb.GetTickerResp.ticker:type_name -> pb.Ticker
	12, // 3: pb.GetDepthResp.asks:type_name -> pb.GetDepthResp.Position
	12, // 4: pb.GetDepthResp.bids:type_name -> pb.GetDepthResp.Position
	9,  // 5: pb.GetTickResp.tick_list:type_name -> pb.Tick
	1,  // 6: pb.QuoteService.GetKline:input_type -> pb.GetKlineReq
	4,  // 7: pb.QuoteService.GetTicker:input_type -> pb.GetTickerReq
	6,  // 8: pb.QuoteService.GetTick:input_type -> pb.GetTickReq
	2,  // 9: pb.QuoteService.GetKline:output_type -> pb.GetKlineResp
	5,  // 10: pb.QuoteService.GetTicker:output_type -> pb.GetTickerResp
	10, // 11: pb.QuoteService.GetTick:output_type -> pb.GetTickResp
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_app_quote_rpc_pb_quote_proto_init() }
func file_app_quote_rpc_pb_quote_proto_init() {
	if File_app_quote_rpc_pb_quote_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_quote_rpc_pb_quote_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKlineReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_quote_rpc_pb_quote_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKlineResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_quote_rpc_pb_quote_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ticker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_quote_rpc_pb_quote_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTickerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_quote_rpc_pb_quote_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTickerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_quote_rpc_pb_quote_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTickReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_quote_rpc_pb_quote_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDepthReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_quote_rpc_pb_quote_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDepthResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_quote_rpc_pb_quote_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_quote_rpc_pb_quote_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTickResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_quote_rpc_pb_quote_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKlineResp_Kline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_quote_rpc_pb_quote_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDepthResp_Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_quote_rpc_pb_quote_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_quote_rpc_pb_quote_proto_goTypes,
		DependencyIndexes: file_app_quote_rpc_pb_quote_proto_depIdxs,
		EnumInfos:         file_app_quote_rpc_pb_quote_proto_enumTypes,
		MessageInfos:      file_app_quote_rpc_pb_quote_proto_msgTypes,
	}.Build()
	File_app_quote_rpc_pb_quote_proto = out.File
	file_app_quote_rpc_pb_quote_proto_rawDesc = nil
	file_app_quote_rpc_pb_quote_proto_goTypes = nil
	file_app_quote_rpc_pb_quote_proto_depIdxs = nil
}
