// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: account.proto

package orderservice

import (
	"context"

	"github.com/nmg988rbdv-svg/go-zero_columbina/app/account/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddUserAssetReq        = pb.AddUserAssetReq
	Asset                  = pb.Asset
	CancelOrderReq         = pb.CancelOrderReq
	CreateOrderReq         = pb.CreateOrderReq
	DeductUserAssetReq     = pb.DeductUserAssetReq
	Empty                  = pb.Empty
	FreezeUserAssetReq     = pb.FreezeUserAssetReq
	FreezeUserAssetResp    = pb.FreezeUserAssetResp
	GetOrderListByUserReq  = pb.GetOrderListByUserReq
	GetOrderListByUserResp = pb.GetOrderListByUserResp
	GetUserAssetListReq    = pb.GetUserAssetListReq
	GetUserAssetListResp   = pb.GetUserAssetListResp
	GetUserAssetReq        = pb.GetUserAssetReq
	GetUserAssetResp       = pb.GetUserAssetResp
	LoginOutReq            = pb.LoginOutReq
	LoginReq               = pb.LoginReq
	LoginResp              = pb.LoginResp
	Order                  = pb.Order
	OrderEmpty             = pb.OrderEmpty
	OrderInfo              = pb.OrderInfo
	RegisterReq            = pb.RegisterReq
	RegisterResp           = pb.RegisterResp
	UnFreezeUserAssetReq   = pb.UnFreezeUserAssetReq
	UpdateOrderStatusReq   = pb.UpdateOrderStatusReq
	ValidateTokenReq       = pb.ValidateTokenReq
	ValidateTokenResp      = pb.ValidateTokenResp

	OrderService interface {
		// 创建订单
		CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*OrderEmpty, error)
		// 获取用户订单列表
		GetOrderList(ctx context.Context, in *GetOrderListByUserReq, opts ...grpc.CallOption) (*GetOrderListByUserResp, error)
		// 取消订单
		CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*OrderEmpty, error)
	}

	defaultOrderService struct {
		cli zrpc.Client
	}
)

func NewOrderService(cli zrpc.Client) OrderService {
	return &defaultOrderService{
		cli: cli,
	}
}

// 创建订单
func (m *defaultOrderService) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*OrderEmpty, error) {
	client := pb.NewOrderServiceClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

// 获取用户订单列表
func (m *defaultOrderService) GetOrderList(ctx context.Context, in *GetOrderListByUserReq, opts ...grpc.CallOption) (*GetOrderListByUserResp, error) {
	client := pb.NewOrderServiceClient(m.cli.Conn())
	return client.GetOrderList(ctx, in, opts...)
}

// 取消订单
func (m *defaultOrderService) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*OrderEmpty, error) {
	client := pb.NewOrderServiceClient(m.cli.Conn())
	return client.CancelOrder(ctx, in, opts...)
}
