// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: app/match/pb/match.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDepthReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 交易对
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// 档位
	Level int32 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *GetDepthReq) Reset() {
	*x = GetDepthReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_match_pb_match_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDepthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepthReq) ProtoMessage() {}

func (x *GetDepthReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_match_pb_match_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepthReq.ProtoReflect.Descriptor instead.
func (*GetDepthReq) Descriptor() ([]byte, []int) {
	return file_app_match_pb_match_proto_rawDescGZIP(), []int{0}
}

func (x *GetDepthReq) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetDepthReq) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type GetDepthResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 订单簿版本
	Version int64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// 卖盘
	Asks []*GetDepthResp_Position `protobuf:"bytes,2,rep,name=asks,proto3" json:"asks,omitempty"`
	// 买盘
	Bids []*GetDepthResp_Position `protobuf:"bytes,3,rep,name=bids,proto3" json:"bids,omitempty"`
}

func (x *GetDepthResp) Reset() {
	*x = GetDepthResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_match_pb_match_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDepthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepthResp) ProtoMessage() {}

func (x *GetDepthResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_match_pb_match_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepthResp.ProtoReflect.Descriptor instead.
func (*GetDepthResp) Descriptor() ([]byte, []int) {
	return file_app_match_pb_match_proto_rawDescGZIP(), []int{1}
}

func (x *GetDepthResp) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetDepthResp) GetAsks() []*GetDepthResp_Position {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *GetDepthResp) GetBids() []*GetDepthResp_Position {
	if x != nil {
		return x.Bids
	}
	return nil
}

type GetDepthResp_Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 数量
	BaseAmount string `protobuf:"bytes,1,opt,name=base_amount,json=baseAmount,proto3" json:"base_amount,omitempty"`
	// 价格
	Price string `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	// 金额
	QuoteAmount string `protobuf:"bytes,3,opt,name=quote_amount,json=quoteAmount,proto3" json:"quote_amount,omitempty"`
}

func (x *GetDepthResp_Position) Reset() {
	*x = GetDepthResp_Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_match_pb_match_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDepthResp_Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepthResp_Position) ProtoMessage() {}

func (x *GetDepthResp_Position) ProtoReflect() protoreflect.Message {
	mi := &file_app_match_pb_match_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepthResp_Position.ProtoReflect.Descriptor instead.
func (*GetDepthResp_Position) Descriptor() ([]byte, []int) {
	return file_app_match_pb_match_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetDepthResp_Position) GetBaseAmount() string {
	if x != nil {
		return x.BaseAmount
	}
	return ""
}

func (x *GetDepthResp_Position) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GetDepthResp_Position) GetQuoteAmount() string {
	if x != nil {
		return x.QuoteAmount
	}
	return ""
}

var File_app_match_pb_match_proto protoreflect.FileDescriptor

var file_app_match_pb_match_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x70, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x70, 0x62, 0x2f, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x22, 0x3b, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0xf2,
	0x01, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x04, 0x61, 0x73, 0x6b,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e,
	0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x30, 0x0a, 0x04, 0x62,
	0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x62, 0x69, 0x64, 0x73, 0x1a, 0x64, 0x0a,
	0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x61, 0x73,
	0x65, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x62, 0x61, 0x73, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x32, 0x43, 0x0a, 0x0c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x12,
	0x12, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x68,
	0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x44,
	0x65, 0x70, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_match_pb_match_proto_rawDescOnce sync.Once
	file_app_match_pb_match_proto_rawDescData = file_app_match_pb_match_proto_rawDesc
)

func file_app_match_pb_match_proto_rawDescGZIP() []byte {
	file_app_match_pb_match_proto_rawDescOnce.Do(func() {
		file_app_match_pb_match_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_match_pb_match_proto_rawDescData)
	})
	return file_app_match_pb_match_proto_rawDescData
}

var file_app_match_pb_match_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_app_match_pb_match_proto_goTypes = []interface{}{
	(*GetDepthReq)(nil),           // 0: match.GetDepthReq
	(*GetDepthResp)(nil),          // 1: match.GetDepthResp
	(*GetDepthResp_Position)(nil), // 2: match.GetDepthResp.Position
}
var file_app_match_pb_match_proto_depIdxs = []int32{
	2, // 0: match.GetDepthResp.asks:type_name -> match.GetDepthResp.Position
	2, // 1: match.GetDepthResp.bids:type_name -> match.GetDepthResp.Position
	0, // 2: match.MatchService.GetDepth:input_type -> match.GetDepthReq
	1, // 3: match.MatchService.GetDepth:output_type -> match.GetDepthResp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_app_match_pb_match_proto_init() }
func file_app_match_pb_match_proto_init() {
	if File_app_match_pb_match_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_match_pb_match_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDepthReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_match_pb_match_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDepthResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_match_pb_match_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDepthResp_Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_match_pb_match_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_match_pb_match_proto_goTypes,
		DependencyIndexes: file_app_match_pb_match_proto_depIdxs,
		MessageInfos:      file_app_match_pb_match_proto_msgTypes,
	}.Build()
	File_app_match_pb_match_proto = out.File
	file_app_match_pb_match_proto_rawDesc = nil
	file_app_match_pb_match_proto_goTypes = nil
	file_app_match_pb_match_proto_depIdxs = nil
}
