// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: account.proto

package server

import (
	"context"

	"github.com/nmg988rbdv-svg/go-zero_columbina/app/account/rpc/internal/logic/orderservice"
	"github.com/nmg988rbdv-svg/go-zero_columbina/app/account/rpc/internal/svc"
	"github.com/nmg988rbdv-svg/go-zero_columbina/app/account/rpc/pb"
)

type OrderServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedOrderServiceServer
}

func NewOrderServiceServer(svcCtx *svc.ServiceContext) *OrderServiceServer {
	return &OrderServiceServer{
		svcCtx: svcCtx,
	}
}

// 创建订单
func (s *OrderServiceServer) CreateOrder(ctx context.Context, in *pb.CreateOrderReq) (*pb.OrderEmpty, error) {
	l := orderservicelogic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

// 获取用户订单列表
func (s *OrderServiceServer) GetOrderList(ctx context.Context, in *pb.GetOrderListByUserReq) (*pb.GetOrderListByUserResp, error) {
	l := orderservicelogic.NewGetOrderListLogic(ctx, s.svcCtx)
	return l.GetOrderList(in)
}

// 取消订单
func (s *OrderServiceServer) CancelOrder(ctx context.Context, in *pb.CancelOrderReq) (*pb.OrderEmpty, error) {
	l := orderservicelogic.NewCancelOrderLogic(ctx, s.svcCtx)
	return l.CancelOrder(in)
}
