// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	account "github.com/nmg988rbdv-svg/go-zero_columbina/app/gateway/internal/handler/account"
	order "github.com/nmg988rbdv-svg/go-zero_columbina/app/gateway/internal/handler/order"
	quote "github.com/nmg988rbdv-svg/go-zero_columbina/app/gateway/internal/handler/quote"
	"github.com/nmg988rbdv-svg/go-zero_columbina/app/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取验证码
				Method:  http.MethodPost,
				Path:    "/get_captcha",
				Handler: account.GetCaptchaHandler(serverCtx),
			},
			{
				// 登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: account.LoginHandler(serverCtx),
			},
			{
				// 注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: account.RegisterHandler(serverCtx),
			},
			{
				// 验证token
				Method:  http.MethodPost,
				Path:    "/validate_token",
				Handler: account.ValidateTokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/account/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 新增用户资产
					Method:  http.MethodPost,
					Path:    "/add_user_asset",
					Handler: account.AddUserAssetHandler(serverCtx),
				},
				{
					// 获取用户所有资产
					Method:  http.MethodPost,
					Path:    "/get_user_asset_list",
					Handler: account.GetUserAssetListHandler(serverCtx),
				},
				{
					// 登出（从 Authorization 读取 token）
					Method:  http.MethodPost,
					Path:    "/logout",
					Handler: account.LoginOutHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/account/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 取消订单
					Method:  http.MethodPost,
					Path:    "/cancel_order",
					Handler: order.CancelOrderHandler(serverCtx),
				},
				{
					// 下单
					Method:  http.MethodPost,
					Path:    "/create_order",
					Handler: order.CreateOrderHandler(serverCtx),
				},
				{
					// 获取用户订单列表
					Method:  http.MethodPost,
					Path:    "/get_order_list",
					Handler: order.GetOrderListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/order/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取k线
				Method:  http.MethodPost,
				Path:    "/get_kline_list",
				Handler: quote.GetKlineListHandler(serverCtx),
			},
			{
				// 获取tick成交
				Method:  http.MethodPost,
				Path:    "/get_tick_list",
				Handler: quote.GetTickListHandler(serverCtx),
			},
			{
				// 获取ticker
				Method:  http.MethodPost,
				Path:    "/get_ticker_list",
				Handler: quote.GetTickerListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/quotes/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取深度
				Method:  http.MethodPost,
				Path:    "/get_depth",
				Handler: quote.GetDepthHandler(serverCtx),
			},
		},
		rest.WithPrefix("/quotes/v1"),
	)
}
