// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: quote.proto

package quoteservice

import (
	"context"

	"github.com/nmg988rbdv-svg/go-zero_columbina/app/quote/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetDepthReq           = pb.GetDepthReq
	GetDepthResp          = pb.GetDepthResp
	GetDepthResp_Position = pb.GetDepthResp_Position
	GetKlineReq           = pb.GetKlineReq
	GetKlineResp          = pb.GetKlineResp
	GetKlineResp_Kline    = pb.GetKlineResp_Kline
	GetTickReq            = pb.GetTickReq
	GetTickResp           = pb.GetTickResp
	GetTickerReq          = pb.GetTickerReq
	GetTickerResp         = pb.GetTickerResp
	Tick                  = pb.Tick
	Ticker                = pb.Ticker

	QuoteService interface {
		// 获取k线
		GetKline(ctx context.Context, in *GetKlineReq, opts ...grpc.CallOption) (*GetKlineResp, error)
		// 获取24小时行情
		GetTicker(ctx context.Context, in *GetTickerReq, opts ...grpc.CallOption) (*GetTickerResp, error)
		// 获取tick
		GetTick(ctx context.Context, in *GetTickReq, opts ...grpc.CallOption) (*GetTickResp, error)
	}

	defaultQuoteService struct {
		cli zrpc.Client
	}
)

func NewQuoteService(cli zrpc.Client) QuoteService {
	return &defaultQuoteService{
		cli: cli,
	}
}

// 获取k线
func (m *defaultQuoteService) GetKline(ctx context.Context, in *GetKlineReq, opts ...grpc.CallOption) (*GetKlineResp, error) {
	client := pb.NewQuoteServiceClient(m.cli.Conn())
	return client.GetKline(ctx, in, opts...)
}

// 获取24小时行情
func (m *defaultQuoteService) GetTicker(ctx context.Context, in *GetTickerReq, opts ...grpc.CallOption) (*GetTickerResp, error) {
	client := pb.NewQuoteServiceClient(m.cli.Conn())
	return client.GetTicker(ctx, in, opts...)
}

// 获取tick
func (m *defaultQuoteService) GetTick(ctx context.Context, in *GetTickReq, opts ...grpc.CallOption) (*GetTickResp, error) {
	client := pb.NewQuoteServiceClient(m.cli.Conn())
	return client.GetTick(ctx, in, opts...)
}
