// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: match.proto

package matchservice

import (
	"context"

	"github.com/nmg988rbdv-svg/go-zero_columbina/app/match/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetDepthReq           = pb.GetDepthReq
	GetDepthResp          = pb.GetDepthResp
	GetDepthResp_Position = pb.GetDepthResp_Position

	MatchService interface {
		// 获取深度
		GetDepth(ctx context.Context, in *GetDepthReq, opts ...grpc.CallOption) (*GetDepthResp, error)
	}

	defaultMatchService struct {
		cli zrpc.Client
	}
)

func NewMatchService(cli zrpc.Client) MatchService {
	return &defaultMatchService{
		cli: cli,
	}
}

// 获取深度
func (m *defaultMatchService) GetDepth(ctx context.Context, in *GetDepthReq, opts ...grpc.CallOption) (*GetDepthResp, error) {
	client := pb.NewMatchServiceClient(m.cli.Conn())
	return client.GetDepth(ctx, in, opts...)
}
