// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddUserAssetReq struct {
	CoinName string `json:"coin_name"`
	Qty      string `json:"qty"`
}

type AssetInfo struct {
	Id           int64  `json:"id"`            //id
	CoinName     string `json:"coin_name"`     //币种名称
	CoinID       int32  `json:"coin_id"`       //币种id
	AvailableQty string `json:"available_qty"` //可用数量
	FrozenQty    string `json:"frozen_qty"`    //冻结数量
}

type CancelOrderReq struct {
	ID         string `json:"id"`          //订单id
	SymbolName string `json:"symbol_name"` //交易对名称
}

type CreateOrderReq struct {
	SymbolName  string `json:"symbol_name" validate:"required"`         //交易对名称
	Price       string `json:"price" validate:"required,numeric"`       //价格
	BaseAmount  string `json:"base_amount" validate:"required,numeric"` //数量
	QuoteAmount string `json:"quote_amount"`                            //金额
	Side        int32  `json:"side" validate:"required,number"`         //方向
	OrderType   int32  `json:"order_type" validate:"required,number"`   //订单类型
}

type Empty struct {
}

type GetCaptchaResp struct {
	CaptchaPic    string `json:"captcha_pic"`
	CaptchaId     string `json:"captcha_id"`
	CaptchaLength int32  `json:"captch_length"`
}

type GetDepthListReq struct {
	Symbol string `json:"symbol"` //交易对
	Level  int32  `json:"level"`  //档位
}

type GetDepthListResp struct {
	Version string      `json:"version"` //当前版本号
	Asks    []*Position `json:"asks"`    //卖盘
	Bids    []*Position `json:"bids"`    //买盘
}

type GetDepthReq struct {
	Symbol string `json:"symbol"`
	Level  int32  `json:"level"`
}

type GetDepthResp struct {
	Version int64            `json:"version"`
	Asks    []*MatchPosition `json:"asks"`
	Bids    []*MatchPosition `json:"bids"`
}

type GetOrderListReq struct {
	Status     []int32 `json:"status_list"` //状态
	SymbolName string  `json:"symbol_name"` //交易对
	PageSize   int64   `json:"page_size"`   //分页偏移量
	Id         string  `json:"id"`          //分页游标，上一页最后一条订单主键ID
}

type GetOrderListResp struct {
	OrderList []*OrderInfo `json:"order_list"`
	Total     int64        `json:"total"`
}

type GetTickReq struct {
	Symbol string `json:"symbol"`         //交易对
	Limit  int32  `json:"limit,optional"` //获取多少条
}

type GetTickResp struct {
	TickList []*TickInfo `json:"tick_list"`
}

type GetTickerListReq struct {
	Symbol string `json:"symbol"` //交易对
}

type GetTickerListResp struct {
	TickerList []*Ticker `json:"ticker_list"`
}

type GetUserAssetListResp struct {
	AssetList []*AssetInfo `json:"asset_list"`
}

type Kline struct {
	Open       string `json:"open"`        //开
	High       string `json:"high"`        //高
	Low        string `json:"low"`         //低
	Close      string `json:"close"`       //收
	Amount     string `json:"amount"`      //成交量
	Volume     string `json:"volume"`      //成交额
	StartTime  int64  `json:"start_time"`  //开始时间
	EndTime    int64  `json:"end_time"`    //结束时间
	PriceRange string `json:"price_range"` //涨跌幅
	Symbol     string `json:"symbol"`      //交易对
}

type KlineListReq struct {
	StartTime int64  `json:"start_time"` //开始时间 秒时间戳
	EndTime   int64  `json:"end_time"`   //结束时间
	KlineType int32  `json:"kline_type"` //k线类型
	Symbol    string `json:"symbol"`     //交易对
}

type KlineListResp struct {
	KlineList []*Kline `json:"kline_list"`
}

type LoginReq struct {
	Username  string `json:"username"`            //用户名
	Password  string `json:"password"`            //密码
	Captcha   string `json:"captcha,optional"`    //验证码
	CaptchaId string `json:"captcha_id,optional"` //验证码ID
}

type LoginResp struct {
	Uid        int64  `json:"uid"`         //用户ID
	Username   string `json:"username"`    //用户名
	Token      string `json:"token"`       //JWT token
	ExpireTime int64  `json:"expire_time"` //token过期时间（Unix秒）
}

type MatchPosition struct {
	BaseAmount  string `json:"base_amount"`
	Price       string `json:"price"`
	QuoteAmount string `json:"quote_amount"`
}

type OrderInfo struct {
	Id                string `json:"id"`                  //id
	OrderId           string `json:"order_id"`            //订单id
	UserId            int64  `json:"user_id"`             //用户id
	SymbolName        string `json:"symbol_name"`         //交易对名
	Price             string `json:"price"`               //价格
	BaseAmount        string `json:"base_amount"`         //数量
	QuoteAmount       string `json:"quote_amount"`        //金额
	Side              int32  `json:"side"`                //方向
	Status            int32  `json:"status"`              // 状态
	OrderType         int32  `json:"order_type"`          //订单类型
	FilledBaseAmount  string `json:"filled_base_amount"`  //成交数量
	FilledQuoteAmount string `json:"filled_quote_amount"` //成交金额
	FilledAvgPrice    string `json:"filled_avg_price"`    //成交均价
	CreatedAt         int64  `json:"created_at"`          //创建时间
}

type Position struct {
	Qty    string `json:"qty"`    //数量
	Price  string `json:"price"`  //价格
	Amount string `json:"amount"` //金额
}

type RegisterReq struct {
	Username        string `json:"username"`              //用户名
	Password        string `json:"password"`              //密码
	ConfirmPassword string `json:"confirm_password"`      //确认密码
	PhoneNumber     int64  `json:"phone_number,optional"` //手机号
	Captcha         int64  `json:"captcha,optional"`      //验证
}

type TickInfo struct {
	Price        string `json:"price"`  //价格
	Qty          string `json:"qty"`    //数量
	Amount       string `json:"amount"` //金额
	Timestamp    int64  `json:"timestamp"`
	Symbol       string `json:"symbol"`
	TakerIsBuyer bool   `json:"taker_is_buyer"`
}

type Ticker struct {
	LastPrice   string `json:"last_price"`   //最新价
	High        string `json:"high"`         //高
	Low         string `json:"low"`          //低
	Amount      string `json:"amount"`       //成交量
	Volume      string `json:"volume"`       //成交额
	PriceRange  string `json:"price_range"`  //涨跌幅
	Last24Price string `json:"last24_price"` //24小时前的价格
	Symbol      string `json:"symbol"`       //交易对
}

type UserInfo struct {
	Uid      int64  `json:"uid"`      //用户ID
	Username string `json:"username"` //用户名
}

type ValidateTokenReq struct {
	Token string `json:"token"` //JWT token
}

type ValidateTokenResp struct {
	UserInfo *UserInfo `json:"user_info"`
}
